name: Generate and Deploy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'
  push:
    branches:
      - main
jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@main
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: '3.10'

      - name: Generate 🏭
        run: |
          git clone https://github.com/kmaehashi/discourse-search-atom.git
          pip install -U pip setuptools
          pip install -r discourse-search-atom/requirements.txt
          export PATH="${PWD}/discourse-search-atom:${PATH}"
          ./.github/workflows/generate.sh

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_generate
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
